# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

root: true
plugins:
  - "@typescript-eslint"
extends: '@cordova/eslint-config/node'

overrides:
  - files: ['**/*.ts']
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: './tsconfig.json'
    rules:
      # This conflicts with a compiler setting for ensuring no unchecked index
      # access, so it has to be disabled or safety will be sacrificed.
      'dot-notation': 'off'
      # ESLint rule needs to be disabled for TypeScript rule to work.
      'no-array-constructor': 'off'
      '@typescript-eslint/no-array-constructor': ['error']
      'no-extra-semi': 'off'
      '@typescript-eslint/no-extra-semi': ['error']
      'no-unused-vars': 'off'
      '@typescript-eslint/no-unused-vars': ['error']
      'no-useless-constructor': 'off'
      '@typescript-eslint/no-useless-constructor': ['error']
      'semi': 'off'
      '@typescript-eslint/semi': ['error']
  - files: [spec/**/*.js]
    extends: '@cordova/eslint-config/node-tests'
